name: CI

# Trigger on push or pull_request to master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
      - run: flutter pub get
      - name: lint
        run: dartanalyzer lib test
      - run: flutter test
      - name: ios-build
        if: matrix.platform == 'macos-latest'
        run: flutter build ios --release --no-codesign
      - name: android-build
        if: matrix.platform == 'ubuntu-latest'
        run: flutter build apk --release --split-per-abi