name: CI

# Trigger on push or pull_request to master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  
  # Install flutter and project deps
  setup:
    runs-on: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
      - run: flutter pub get
  
  # Lint (Android only)
  lint:
    needs: setup
    runs-on: [ubuntu-latest]
    steps:
      - run: dartanalyzer lib test
  
  # Unit test (Android only)
  test:
    needs: setup
    runs-on: [ubuntu-latest]
    steps:
      - run: flutter test

  # iOS build
  ios-build:
    needs: setup
    runs-on: [macos-latest]
    steps:
      - run: flutter build ios --release --no-codesign

  # Android build
  android-build:
    needs: [lint, test]
    runs-on: [ubuntu-latest]
    steps:
      - run: flutter build apk --release --split-per-abi
